# Generated by Django 4.2.26 on 2025-11-26 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0004_alter_workers_wages_type'),
        ('globals', '0003_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('project_type', models.CharField(choices=[(10, 'House'), (20, 'Floor'), (30, 'Mixed (House + Floors)')], default='mixed', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_sqyd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('price_sqyd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('facing', models.CharField(blank=True, max_length=50)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/projects/')),
                ('layout', models.ImageField(blank=True, null=True, upload_to='images/projects/')),
                ('gallery_images', models.JSONField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(10, 'Under Constraction'), (20, 'Completed'), (30, 'Hold')], default=10)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wages_type', models.SmallIntegerField(choices=[(10, 'Per Day'), (20, 'Per Hour'), (30, 'Per SQ FT'), (40, 'Lum Sum')], default=10)),
                ('wages', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(10, 'Active'), (20, 'Inactive'), (30, 'Deleted')], default=10)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='Project')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workers', verbose_name='Amenity')),
            ],
            options={
                'verbose_name': 'Project Amenity',
                'verbose_name_plural': 'Project Amenities',
            },
        ),
        migrations.CreateModel(
            name='ProjectHouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.IntegerField()),
                ('area_sqyd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('builtup_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimension', models.CharField(blank=True, max_length=100, null=True)),
                ('bedrooms', models.IntegerField(default=2)),
                ('bathrooms', models.IntegerField(default=2)),
                ('Kitchen', models.IntegerField(default=1)),
                ('balconies', models.IntegerField(default=0)),
                ('parking', models.BooleanField(default=True)),
                ('total_floors', models.SmallIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('house_images', models.JSONField(blank=True, null=True)),
                ('layout', models.ImageField(blank=True, null=True, upload_to='images/projects/house/')),
                ('complete_percentage', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(10, 'Available'), (20, 'Agrement'), (30, 'Sold'), (40, 'Hold')], default=10)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('amenity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.amenities', verbose_name='Amenity')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Amenity',
                'verbose_name_plural': 'Project Amenities',
            },
        ),
    ]
