# Generated by Django 4.2.26 on 2025-11-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_amenities'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='globals.cities'),
        ),
        migrations.AddField(
            model_name='projects',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='globals.countries'),
        ),
        migrations.AddField(
            model_name='projects',
            name='locality_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locality', to='globals.localities'),
        ),
        migrations.AddField(
            model_name='projects',
            name='state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='globals.states'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.SmallIntegerField(choices=[(10, 'House'), (20, 'Floor'), (30, 'Mixed (House + Floors)')], default='mixed'),
        ),
    ]
