# Generated by Django 4.2.26 on 2025-11-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_amenities'),
        ('projects', '0002_projects_city_id_projects_country_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthouses',
            options={'verbose_name': 'Project Houses', 'verbose_name_plural': 'Project Houses'},
        ),
        migrations.AlterModelOptions(
            name='projectworkers',
            options={'verbose_name': 'Project Worker', 'verbose_name_plural': 'Project Workers'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='globals.cities', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='globals.countries', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='locality_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locality', to='globals.localities', verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='globals.states', verbose_name='State'),
        ),
    ]
