# Generated by Django 4.2.26 on 2025-11-30 15:34

import common.filters.adminModelFilter
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projecthouses_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Image'), (2, 'Video'), (3, 'PDF')], default=1)),
                ('file', models.FileField(upload_to='images/projects/Gallery/', validators=[common.filters.adminModelFilter.validate_file_extension])),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Media',
                'verbose_name_plural': 'Project Media',
            },
        ),
    ]
