# Generated by Django 4.2.26 on 2025-12-01 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkerAttendances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('paid_amount', models.IntegerField(blank=True, null=True)),
                ('remaining_amount', models.IntegerField(blank=True, null=True)),
                ('working_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('project_worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectworkers', verbose_name='ProjectWorker')),
            ],
            options={
                'verbose_name': 'Project Worker Attendance',
                'verbose_name_plural': 'Project Worker Attendances',
            },
        ),
    ]
