# Generated by Django 4.2.26 on 2025-12-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_workers_wages_type'),
        ('projects', '0007_projectworkerattendances_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkerattendances',
            name='worker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.workers', verbose_name='Worker'),
        ),
    ]
