# Generated by Django 4.2.26 on 2025-12-16 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_avatar'),
        ('projects', '0008_alter_projectworkerattendances_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthouses',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='customers.customers'),
        ),
    ]
