# Generated by Django 4.2.26 on 2025-12-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projecthouses_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.SmallIntegerField(choices=[(10, 'Under Constraction'), (20, 'Completed'), (30, 'Hold'), (40, 'Up Coming')], default=10),
        ),
    ]
