# Generated by Django 4.2.26 on 2025-12-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projects_description_alter_projects_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmedia',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
