# Generated by Django 4.2.26 on 2025-12-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectmedia_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectworkerattendances',
            name='worker_id',
        ),
    ]
