# Generated by Django 4.2.26 on 2025-12-17 05:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_materials'),
        ('projects', '0013_projectworkerattendances_worker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity received', max_digits=10)),
                ('unit', models.CharField(blank=True, help_text='Bags / Tons / CFT / Kg', max_length=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per unit', max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.SmallIntegerField(choices=[(10, 'Pending'), (20, 'Partial'), (30, 'Paid')], default=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, help_text='Site supervisor / store keeper', max_length=255, null=True)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='globals.materials')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_material', to='projects.projects')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='globals.suppliers')),
                ('vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='globals.vehicles')),
            ],
            options={
                'verbose_name': 'Project Material',
                'verbose_name_plural': 'Project Materials',
                'ordering': ['-received_date'],
            },
        ),
    ]
