# Generated by Django 4.2.26 on 2025-12-17 06:15

import common.filters.adminModelFilter
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaterials',
            name='bill_image',
            field=models.FileField(blank=True, null=True, upload_to='images/projects/Gallery/', validators=[common.filters.adminModelFilter.validate_image_format]),
        ),
    ]
