# Generated by Django 4.2.26 on 2025-12-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projects_assigned_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='assigned_user',
        ),
    ]
