# Generated by Django 4.2.26 on 2026-02-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_projects_assigned_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmaterials',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='projectmaterials',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='projectmaterials',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='projectmaterials',
            name='unit',
        ),
        migrations.AddField(
            model_name='projectmaterials',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='projectmaterials',
            name='round_total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmaterials',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
