# Generated by Django 4.2.26 on 2026-02-02 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_alter_suppliers_brand_id'),
        ('projects', '0019_remove_projectmaterials_material_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterialLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity received', max_digits=10)),
                ('unit', models.CharField(blank=True, help_text='Bags / Tons / CFT / Kg', max_length=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per unit', max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='globals.materials')),
                ('project_material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_material_id', to='projects.projectmaterials')),
            ],
            options={
                'verbose_name': 'Project Material List',
                'verbose_name_plural': 'Project Material Lists',
            },
        ),
    ]
