# Generated by Django 4.2.26 on 2026-04-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projectmateriallists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.SmallIntegerField(choices=[(10, 'House'), (20, 'Floor'), (30, 'Mixed (House + Floors)')], default=30),
        ),
    ]
