# Generated by Django 4.2.26 on 2026-04-11 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_alter_suppliers_brand_id'),
        ('projects', '0021_alter_projects_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSupplierLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(help_text='Details of the items received')),
                ('item_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ledgers', to='projects.projects')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ledgers', to='globals.suppliers')),
            ],
            options={
                'verbose_name': 'Project Supplier Ledger',
                'verbose_name_plural': 'Project Supplier Ledgers',
                'ordering': ['-item_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.projectsupplierledger')),
            ],
            options={
                'verbose_name': 'Project Supplier Payment',
                'verbose_name_plural': 'Project Supplier Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('SUPPLIER_PAYMENT', 'Supplier Payment'), ('WORKER_PAYMENT', 'Worker Payment'), ('OTHER_EXPENSE', 'Other Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_date', models.DateField()),
                ('description', models.TextField()),
                ('reference_type', models.CharField(help_text='Model name e.g., supplier or worker', max_length=50)),
                ('reference_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='projects.projects')),
                ('supplier_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='projects.projectsupplierpayment')),
                ('worker_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='projects.projectworkerattendances')),
            ],
            options={
                'verbose_name': 'Project Ledger',
                'verbose_name_plural': 'Project Ledgers',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
