# Generated by Django 4.2.26 on 2026-04-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectsupplierledger_projectsupplierpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectledger',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectledger',
            name='reference_type',
            field=models.CharField(blank=True, help_text='Model name e.g., supplier or worker', max_length=50, null=True),
        ),
    ]
