# Generated by Django 4.2.26 on 2026-04-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_workers_created_by'),
        ('projects', '0023_alter_projectledger_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkers',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workers', to='projects.projects', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectworkers',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workers', to='workers.workers', verbose_name='Worker'),
        ),
    ]
