# Generated by Django 4.2.26 on 2026-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_projectworkerattendances_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworkers',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area (Sq Ft)'),
        ),
    ]
