# Generated by Django 4.2.26 on 2025-12-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_materials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
    ]
