# Generated by Django 4.2.26 on 2025-12-17 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_alter_materials_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.brands', verbose_name='Brand'),
        ),
    ]
