"""
Django settings for sidhivinayak project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from django.forms.renderers import TemplatesSetting

from django.contrib import admin
admin.ModelAdmin.save_on_top = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['13.235.165.205', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "accounts.apps.AccountsConfig",
    "customers.apps.CustomersConfig",
    "contractor.apps.ContractorConfig",
    "projects.apps.ProjectsConfig",
    "workers.apps.WorkersConfig",
    "globals.apps.GlobalsConfig",
    "common",
    "reports",
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

JAZZMIN_SETTINGS = {
    "welcome_sign": "Welcome to Siddhi Vinayak Estate Developers",
    "show_sidebar": True,
    "navigation_expanded": False,
    "show_ui_builder": True,

    "site_title": "Siddhi Vinayak Estate Developers Admin",
    "site_header": "Siddhi Vinayak Estate Developers",
    "site_logo": "assets/images/logo.jpg",  # Relative to STATIC_URL
    "site_logo_classes": " bg-white",  # Optional
    "login_logo": "assets/images/logo.jpg",       # Login page logo
    "login_logo_dark": "assets/images/logo.jpg",  # Dark mode logo

    # Optional
    "site_brand": "SVED",
    "custom_css": "css/admin_custom.css",

    # Sidebar Icon mapping
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-user-shield",
        
        # Accounts
        "accounts.UserLedger": "fas fa-book",
        "accounts.UserLedgerTransaction": "fas fa-exchange-alt",
        
        # Projects
        "projects.Projects": "fas fa-building",
        "projects.ProjectHouses": "fas fa-home",
        "projects.ProjectWorkerAttendances": "fas fa-calendar-check",
        "projects.ProjectMaterials": "fas fa-toolbox",
        "projects.UserProjectPermissions": "fas fa-user-lock",
        "projects.ProjectSupplierLedger": "fas fa-truck-loading",
        "projects.ProjectLedger": "fas fa-file-invoice-rupee",
        
        # Contractor
        "contractor.Projects": "fas fa-construction",
        "contractor.ProjectWorkerAttendances": "fas fa-user-check",
        
        # Customers
        "customers.Customers": "fas fa-user-tie",
        "customers.CustomerEnquiry": "fas fa-phone-alt",
        "customers.PropertySellRequest": "fas fa-city",
        "customers.CustomerLedger": "fas fa-book-open",
        "customers.CustomerLedgerTransaction": "fas fa-money-bill-wave",
        "customers.CustomerRequestTransaction": "fas fa-hand-holding-usd",
        
        # Workers
        "workers.Workers": "fas fa-hard-hat",
        "workers.WorkerTypes": "fas fa-id-badge",
        
        # Globals
        "globals.Cities": "fas fa-map-marker-alt",
        "globals.Contacts": "fas fa-address-book",
        "globals.Countries": "fas fa-flag",
        "globals.Regions": "fas fa-map",
        "globals.States": "fas fa-map-signs",
        "globals.Suppliers": "fas fa-store",
        "globals.Vehicles": "fas fa-truck",
        "globals.Localities": "fas fa-street-view",
        "globals.Amenities": "fas fa-swimming-pool",
        "globals.Materials": "fas fa-cubes",

        # Reports
        "reports.UserCustomerLedger": "fas fa-chart-bar",
    },
    
    # Default icons for apps and models that don't have one
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    
    # Sidebar order
    "order_with_respect_to": [
        "auth",
        "accounts",
        "projects",
        "contractor",
        "customers",
        "workers",
        "globals",
        "reports",
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'common.middleware.current_user.CurrentUserMiddleware',
]

ROOT_URLCONF = 'sidhivinayak.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],        # add dir path for custom templates.
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sidhivinayak.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",   # jaha aap manually static files likhte ho
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # 👈 collectstatic inko yaha copy karega


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FORM_RENDERER = "sidhivinayak.settings.TemplatesSetting"
