# Generated by Django 4.2.26 on 2025-12-25 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.SmallIntegerField(choices=[(10, 'House'), (20, 'Floor'), (30, 'Mixed (House + Floors)')], default='mixed')),
                ('address', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('area_sqyd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/projects/')),
                ('layout', models.ImageField(blank=True, null=True, upload_to='images/projects/')),
                ('status', models.SmallIntegerField(choices=[(10, 'Under Constraction'), (20, 'Completed'), (30, 'Hold'), (40, 'Up Coming')], default=10)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Contractor Project',
                'verbose_name_plural': 'Contractor Projects',
            },
        ),
    ]
