# Generated by Django 4.2.26 on 2025-12-25 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_workers_wages_type'),
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wages_type', models.SmallIntegerField(choices=[(10, 'Per Day'), (20, 'Per Hour'), (30, 'Per SQ FT'), (40, 'Lum Sum')], default=10)),
                ('wages', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(10, 'Active'), (20, 'Inactive'), (30, 'Deleted')], default=10)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contractor_project', to='contractor.projects', verbose_name='Project')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contractor_project_worker', to='workers.workers', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Project Worker',
                'verbose_name_plural': 'Project Workers',
            },
        ),
    ]
