# Generated by Django 4.2.26 on 2025-12-25 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_workers_wages_type'),
        ('contractor', '0002_projectworkers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkerAttendances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('working_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_project_id', to='contractor.projects', verbose_name='Project')),
                ('project_worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_project_worker', to='contractor.projectworkers', verbose_name='ProjectWorker')),
                ('worker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_project_worker_id', to='workers.workers', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Project Worker Attendance',
                'verbose_name_plural': 'Project Worker Attendances',
            },
        ),
    ]
