# Generated by Django 4.2.26 on 2026-04-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_projectworkerattendances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.SmallIntegerField(choices=[(10, 'House'), (20, 'Floor'), (30, 'Mixed (House + Floors)')], default=30),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.SmallIntegerField(choices=[(10, 'Under Construction'), (20, 'Completed'), (30, 'Hold'), (40, 'Upcoming')], default=10),
        ),
    ]
