# Generated by Django 4.2.26 on 2026-04-28 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_projectworkers_project_id_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='created_supplier_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_pending_transactions', to='projects.projectsupplierpayment'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='created_worker_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_pending_transactions', to='projects.projectworkerattendances'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='kind',
            field=models.CharField(choices=[('customer_txn', 'Customer Ledger Transaction'), ('supplier_payment', 'Supplier Payment'), ('worker_attendance', 'Worker Attendance')], default='customer_txn', max_length=32),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='payload',
            field=models.JSONField(help_text='Proposed payload. Shape depends on `kind` - see propose_* tool implementations in chat/services/tools.py.'),
        ),
    ]
