# Generated by Django 4.2.26 on 2026-03-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLedgerTransactions',
            new_name='UserLedgerTransaction',
        ),
    ]
