# Generated by Django 4.2.26 on 2026-03-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userledgertransactions_userledgertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userledgertransaction',
            name='payed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
