# Generated by Django 4.2.26 on 2026-03-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userledgertransaction_payed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userledgertransaction',
            name='payed_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
