# Generated by Django 4.2.26 on 2026-03-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userledgertransaction_payed_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userledgertransaction',
            old_name='payed_on',
            new_name='paid_on',
        ),
    ]
