# Generated by Django 4.2.26 on 2026-03-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_payed_on_userledgertransaction_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userledgertransaction',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
