# Generated by Django 4.2.26 on 2026-04-23 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customerrequesttransaction_status'),
        ('accounts', '0006_alter_userledgertransaction_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='userledgertransaction',
            name='source_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ledger_entries', to='customers.customerledgertransaction'),
        ),
    ]
