# Generated by Django 4.2.26 on 2026-05-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userledgertransaction_source_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userledgertransaction',
            name='mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
