# Generated by Django 4.2.26 on 2025-12-16 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('auth_key', models.CharField(max_length=32)),
                ('password_hash', models.CharField(max_length=255)),
                ('password_reset_token', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('alt_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.SmallIntegerField(choices=[(10, 'Active'), (20, 'Inactive'), (30, 'Deleted')], default=10)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='customers_c_usernam_0c91b8_idx'), models.Index(fields=['email'], name='customers_c_email_5ca764_idx')],
            },
        ),
    ]
