# Generated by Django 4.2.26 on 2025-12-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/customers/'),
        ),
    ]
