# Generated by Django 4.2.26 on 2025-12-16 06:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projects_description_alter_projects_status'),
        ('customers', '0002_alter_customers_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('alt_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('property_type', models.SmallIntegerField(choices=[(10, 'Flat'), (20, 'House'), (30, 'Plot')])),
                ('address', models.TextField(blank=True)),
                ('area_sqyd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimension', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reason_for_selling', models.CharField(blank=True, help_text='Urgent / Investment Exit / Other', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Broker notes / negotiation points')),
                ('status', models.SmallIntegerField(choices=[(10, 'New Lead'), (20, 'Contacted'), (30, 'Site Visit'), (40, 'Deal Closed'), (50, 'Rejected')], default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Agar property kisi known project me hai', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projects')),
            ],
            options={
                'verbose_name': 'Property Sell Request',
                'verbose_name_plural': 'Property Sell Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('requirement', models.TextField(help_text='Client requirement / expectation')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('plot', 'Plot')], default='residential', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('status', models.SmallIntegerField(choices=[(10, 'New'), (20, 'Contacted'), (30, 'Interested'), (40, 'Not Interested'), (500, 'Converted')], default=10)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='Project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
