# Generated by Django 4.2.26 on 2025-12-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_propertysellrequest_customerenquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerenquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Enquiry', 'verbose_name_plural': 'Customer Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
