# Generated by Django 4.2.26 on 2025-12-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customerenquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerenquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerenquiry',
            name='phone_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
