# Generated by Django 4.2.26 on 2025-12-26 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0005_alter_customerenquiry_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerenquiry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_enquiry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertysellrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_property_sell_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
