# Generated by Django 4.2.26 on 2026-03-27 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projectmateriallists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0006_customerenquiry_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ledgers', to='customers.customers')),
                ('project_house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projecthouses', verbose_name='Project_house_ledger')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='Project_customer_ledger')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('credited', 'Credited'), ('debited', 'Debited')], default='credited', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detail', models.TextField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='customers.customerledger')),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_to_transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
