# Generated by Django 4.2.26 on 2026-04-03 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0007_customerledger_customerledgertransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledgertransaction',
            name='customer_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ledger_transactions', to='customers.customerledger'),
        ),
        migrations.CreateModel(
            name='CustomerRequestTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('credited', 'Credited'), ('debited', 'Debited')], default='credited', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detail', models.TextField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='customers.customerledger')),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
