# Generated by Django 4.2.26 on 2026-04-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customerledgertransaction_customer_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequesttransaction',
            name='status',
            field=models.SmallIntegerField(choices=[(10, 'New'), (20, 'Accepted'), (30, 'Deleted')], default=10),
        ),
    ]
