# Generated by Django 4.2.26 on 2026-05-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customerrequesttransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledgertransaction',
            name='mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerrequesttransaction',
            name='mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
