# Generated by Django 4.2.26 on 2026-05-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_add_mode_to_ledger_and_request_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Loan Amount'),
        ),
    ]
