# Generated by Django 4.2.26 on 2026-05-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customerledger_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='last_active_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Active'),
        ),
        migrations.AddField(
            model_name='customers',
            name='last_login_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
    ]
