STATUS_ACTIVE = 10
STATUS_ACTIVE_LABEL = "Active"
STATUS_INACTIVE = 20
STATUS_INACTIVE_LABEL = "In-Active"
STATUS_DELETE = 30
STATUS_DELETE_LABEL = "Deleted"

STATUS_IN_STOCK = 40
STATUS_IN_STOCK_LABEL = "In-Stock"
STATUS_OUT_OF_STOCK = 50
STATUS_OUT_OF_STOCK_LABEL = "Out-Of-Stock"

PAYMENT_STATUS_PAID = 60
PAYMENT_STATUS_PAID_LABEL = "Paid"
PAYMENT_STATUS_PARTIAL_PAID = 70
PAYMENT_STATUS_PARTIAL_PAID_LABEL = "Partial Paid"
PAYMENT_STATUS_UNPAID = 80
PAYMENT_STATUS_UNPAID_LABEL = "Unpaid"

RENTAL_STATUS_ON_GOING = 90
RENTAL_STATUS_ON_GOING_LABEL = "On-Going"
RENTAL_STATUS_COMPLETED = 100
RENTAL_STATUS_COMPLETED_LABEL = "Completed"
RENTAL_STATUS_CANCELLED = 110
RENTAL_STATUS_CANCELLED_LABEL = "Cancelled"
