# Generated by Django 4.2.26 on 2025-11-25 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workertypes',
            options={'verbose_name': 'Worker Type', 'verbose_name_plural': 'Worker Types'},
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wages', models.IntegerField()),
                ('ratting', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10-digit mobile number.', regex='^[6-9]\\d{9}$')])),
                ('status', models.SmallIntegerField(choices=[(10, 'Active'), (20, 'Inactive'), (30, 'Deleted')], default=10)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('worker_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workertypes', verbose_name='worker')),
            ],
        ),
    ]
