# Generated by Django 4.2.26 on 2025-11-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_workertypes_options_workers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AddField(
            model_name='workers',
            name='wages_type',
            field=models.SmallIntegerField(choices=[(10, 'Per Day'), (20, 'Per Hour'), (30, 'Per SQ FT')], default=10),
        ),
    ]
