# Generated by Django 4.2.26 on 2025-11-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_workers_options_workers_wages_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='wages_type',
            field=models.SmallIntegerField(choices=[(10, 'Per Day'), (20, 'Per Hour'), (30, 'Per SQ FT'), (40, 'Lum Sum')], default=10),
        ),
    ]
